using DreamersCode.Utilities.Lookups.Countries.Models;
#if NET8_0_OR_GREATER
using System.Collections.Frozen;
#endif
using System.Collections.Generic;

namespace DreamersCode.Utilities.Lookups.Countries
{
    /// <summary>
    /// Contains a list of all the countries against which queries can be made
    /// </summary>
    public static class CountryCollection
    {
#if NET8_0_OR_GREATER
        /// <summary>
        /// Represents the set of countries as per ISO-3166
        /// </summary>
        public static FrozenSet<Country> AllCountries { get; internal set; }
#else
        /// <summary>
        /// Represents the set of countries as per ISO-3166
        /// </summary>
        public static IReadOnlyCollection<Country> AllCountries { get; internal set; }
#endif

        /// <summary>
        /// Constructor
        /// </summary>
        static CountryCollection()
        {
            var countries = new List<Country>()
            {
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Afghanistan")},  twoLetterCode:"AF", threeLetterCode:"AFG", numericCode:4),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Albania")},  twoLetterCode:"AL", threeLetterCode:"ALB", numericCode:8),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Antarctica")},  twoLetterCode:"AQ", threeLetterCode:"ATA", numericCode:10),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Algeria")},  twoLetterCode:"DZ", threeLetterCode:"DZA", numericCode:12),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "American Samoa")},  twoLetterCode:"AS", threeLetterCode:"ASM", numericCode:16),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Andorra")},  twoLetterCode:"AD", threeLetterCode:"AND", numericCode:20),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Angola")},  twoLetterCode:"AO", threeLetterCode:"AGO", numericCode:24),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Antigua and Barbuda")},  twoLetterCode:"AG", threeLetterCode:"ATG", numericCode:28),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Azerbaijan")},  twoLetterCode:"AZ", threeLetterCode:"AZE", numericCode:31),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Argentina")},  twoLetterCode:"AR", threeLetterCode:"ARG", numericCode:32),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Australia")},  twoLetterCode:"AU", threeLetterCode:"AUS", numericCode:36),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Austria")},  twoLetterCode:"AT", threeLetterCode:"AUT", numericCode:40),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Bahamas (the)")},  twoLetterCode:"BS", threeLetterCode:"BHS", numericCode:44),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Bahrain")},  twoLetterCode:"BH", threeLetterCode:"BHR", numericCode:48),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Bangladesh")},  twoLetterCode:"BD", threeLetterCode:"BGD", numericCode:50),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Armenia")},  twoLetterCode:"AM", threeLetterCode:"ARM", numericCode:51),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Barbados")},  twoLetterCode:"BB", threeLetterCode:"BRB", numericCode:52),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Belgium")},  twoLetterCode:"BE", threeLetterCode:"BEL", numericCode:56),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Bermuda")},  twoLetterCode:"BM", threeLetterCode:"BMU", numericCode:60),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Bhutan")},  twoLetterCode:"BT", threeLetterCode:"BTN", numericCode:64),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Bolivia (Plurinational State of)")},  twoLetterCode:"BO", threeLetterCode:"BOL", numericCode:68),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Bosnia and Herzegovina")},  twoLetterCode:"BA", threeLetterCode:"BIH", numericCode:70),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Botswana")},  twoLetterCode:"BW", threeLetterCode:"BWA", numericCode:72),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Bouvet Island")},  twoLetterCode:"BV", threeLetterCode:"BVT", numericCode:74),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Brazil")},  twoLetterCode:"BR", threeLetterCode:"BRA", numericCode:76),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Belize")},  twoLetterCode:"BZ", threeLetterCode:"BLZ", numericCode:84),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "British Indian Ocean Territory (the)")},  twoLetterCode:"IO", threeLetterCode:"IOT", numericCode:86),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Solomon Islands")},  twoLetterCode:"SB", threeLetterCode:"SLB", numericCode:90),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Virgin Islands (British)")},  twoLetterCode:"VG", threeLetterCode:"VGB", numericCode:92),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Brunei Darussalam")},  twoLetterCode:"BN", threeLetterCode:"BRN", numericCode:96),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Bulgaria")},  twoLetterCode:"BG", threeLetterCode:"BGR", numericCode:100),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Myanmar")},  twoLetterCode:"MM", threeLetterCode:"MMR", numericCode:104),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Burundi")},  twoLetterCode:"BI", threeLetterCode:"BDI", numericCode:108),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Belarus")},  twoLetterCode:"BY", threeLetterCode:"BLR", numericCode:112),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Cambodia")},  twoLetterCode:"KH", threeLetterCode:"KHM", numericCode:116),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Cameroon")},  twoLetterCode:"CM", threeLetterCode:"CMR", numericCode:120),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Canada")},  twoLetterCode:"CA", threeLetterCode:"CAN", numericCode:124),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Cabo Verde")},  twoLetterCode:"CV", threeLetterCode:"CPV", numericCode:132),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Cayman Islands (the)")},  twoLetterCode:"KY", threeLetterCode:"CYM", numericCode:136),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Central African Republic (the)")},  twoLetterCode:"CF", threeLetterCode:"CAF", numericCode:140),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Sri Lanka")},  twoLetterCode:"LK", threeLetterCode:"LKA", numericCode:144),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Chad")},  twoLetterCode:"TD", threeLetterCode:"TCD", numericCode:148),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Chile")},  twoLetterCode:"CL", threeLetterCode:"CHL", numericCode:152),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "China")},  twoLetterCode:"CN", threeLetterCode:"CHN", numericCode:156),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Taiwan (Province of China)")},  twoLetterCode:"TW", threeLetterCode:"TWN", numericCode:158),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Christmas Island")},  twoLetterCode:"CX", threeLetterCode:"CXR", numericCode:162),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Cocos (Keeling) Islands (the)")},  twoLetterCode:"CC", threeLetterCode:"CCK", numericCode:166),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Colombia")},  twoLetterCode:"CO", threeLetterCode:"COL", numericCode:170),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Comoros (the)")},  twoLetterCode:"KM", threeLetterCode:"COM", numericCode:174),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Mayotte")},  twoLetterCode:"YT", threeLetterCode:"MYT", numericCode:175),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Congo (the)")},  twoLetterCode:"CG", threeLetterCode:"COG", numericCode:178),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Congo (the Democratic Republic of the)")},  twoLetterCode:"CD", threeLetterCode:"COD", numericCode:180),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Cook Islands (the)")},  twoLetterCode:"CK", threeLetterCode:"COK", numericCode:184),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Costa Rica")},  twoLetterCode:"CR", threeLetterCode:"CRI", numericCode:188),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Croatia")},  twoLetterCode:"HR", threeLetterCode:"HRV", numericCode:191),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Cuba")},  twoLetterCode:"CU", threeLetterCode:"CUB", numericCode:192),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Cyprus")},  twoLetterCode:"CY", threeLetterCode:"CYP", numericCode:196),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Czechia")},  twoLetterCode:"CZ", threeLetterCode:"CZE", numericCode:203),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Benin")},  twoLetterCode:"BJ", threeLetterCode:"BEN", numericCode:204),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Denmark")},  twoLetterCode:"DK", threeLetterCode:"DNK", numericCode:208),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Dominica")},  twoLetterCode:"DM", threeLetterCode:"DMA", numericCode:212),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Dominican Republic (the)")},  twoLetterCode:"DO", threeLetterCode:"DOM", numericCode:214),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Ecuador")},  twoLetterCode:"EC", threeLetterCode:"ECU", numericCode:218),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "El Salvador")},  twoLetterCode:"SV", threeLetterCode:"SLV", numericCode:222),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Equatorial Guinea")},  twoLetterCode:"GQ", threeLetterCode:"GNQ", numericCode:226),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Ethiopia")},  twoLetterCode:"ET", threeLetterCode:"ETH", numericCode:231),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Eritrea")},  twoLetterCode:"ER", threeLetterCode:"ERI", numericCode:232),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Estonia")},  twoLetterCode:"EE", threeLetterCode:"EST", numericCode:233),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Faroe Islands (the)")},  twoLetterCode:"FO", threeLetterCode:"FRO", numericCode:234),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Falkland Islands (the) [Malvinas]")},  twoLetterCode:"FK", threeLetterCode:"FLK", numericCode:238),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "South Georgia and the South Sandwich Islands")},  twoLetterCode:"GS", threeLetterCode:"SGS", numericCode:239),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Fiji")},  twoLetterCode:"FJ", threeLetterCode:"FJI", numericCode:242),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Finland")},  twoLetterCode:"FI", threeLetterCode:"FIN", numericCode:246),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Åland Islands")},  twoLetterCode:"AX", threeLetterCode:"ALA", numericCode:248),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "France")},  twoLetterCode:"FR", threeLetterCode:"FRA", numericCode:250),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "French Guiana")},  twoLetterCode:"GF", threeLetterCode:"GUF", numericCode:254),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "French Polynesia")},  twoLetterCode:"PF", threeLetterCode:"PYF", numericCode:258),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "French Southern Territories (the)")},  twoLetterCode:"TF", threeLetterCode:"ATF", numericCode:260),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Djibouti")},  twoLetterCode:"DJ", threeLetterCode:"DJI", numericCode:262),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Gabon")},  twoLetterCode:"GA", threeLetterCode:"GAB", numericCode:266),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Georgia")},  twoLetterCode:"GE", threeLetterCode:"GEO", numericCode:268),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Gambia (the)")},  twoLetterCode:"GM", threeLetterCode:"GMB", numericCode:270),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Palestine, State of")},  twoLetterCode:"PS", threeLetterCode:"PSE", numericCode:275),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Germany")},  twoLetterCode:"DE", threeLetterCode:"DEU", numericCode:276),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Ghana")},  twoLetterCode:"GH", threeLetterCode:"GHA", numericCode:288),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Gibraltar")},  twoLetterCode:"GI", threeLetterCode:"GIB", numericCode:292),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Kiribati")},  twoLetterCode:"KI", threeLetterCode:"KIR", numericCode:296),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Greece")},  twoLetterCode:"GR", threeLetterCode:"GRC", numericCode:300),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Greenland")},  twoLetterCode:"GL", threeLetterCode:"GRL", numericCode:304),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Grenada")},  twoLetterCode:"GD", threeLetterCode:"GRD", numericCode:308),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Guadeloupe")},  twoLetterCode:"GP", threeLetterCode:"GLP", numericCode:312),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Guam")},  twoLetterCode:"GU", threeLetterCode:"GUM", numericCode:316),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Guatemala")},  twoLetterCode:"GT", threeLetterCode:"GTM", numericCode:320),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Guinea")},  twoLetterCode:"GN", threeLetterCode:"GIN", numericCode:324),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Guyana")},  twoLetterCode:"GY", threeLetterCode:"GUY", numericCode:328),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Haiti")},  twoLetterCode:"HT", threeLetterCode:"HTI", numericCode:332),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Heard Island and McDonald Islands")},  twoLetterCode:"HM", threeLetterCode:"HMD", numericCode:334),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Holy See (the)")},  twoLetterCode:"VA", threeLetterCode:"VAT", numericCode:336),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Honduras")},  twoLetterCode:"HN", threeLetterCode:"HND", numericCode:340),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Hong Kong")},  twoLetterCode:"HK", threeLetterCode:"HKG", numericCode:344),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Hungary")},  twoLetterCode:"HU", threeLetterCode:"HUN", numericCode:348),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Iceland")},  twoLetterCode:"IS", threeLetterCode:"ISL", numericCode:352),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "India")},  twoLetterCode:"IN", threeLetterCode:"IND", numericCode:356),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Indonesia")},  twoLetterCode:"ID", threeLetterCode:"IDN", numericCode:360),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Iran (Islamic Republic of)")},  twoLetterCode:"IR", threeLetterCode:"IRN", numericCode:364),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Iraq")},  twoLetterCode:"IQ", threeLetterCode:"IRQ", numericCode:368),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Ireland")},  twoLetterCode:"IE", threeLetterCode:"IRL", numericCode:372),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Israel")},  twoLetterCode:"IL", threeLetterCode:"ISR", numericCode:376),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Italy")},  twoLetterCode:"IT", threeLetterCode:"ITA", numericCode:380),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Côte d'Ivoire")},  twoLetterCode:"CI", threeLetterCode:"CIV", numericCode:384),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Jamaica")},  twoLetterCode:"JM", threeLetterCode:"JAM", numericCode:388),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Japan")},  twoLetterCode:"JP", threeLetterCode:"JPN", numericCode:392),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Kazakhstan")},  twoLetterCode:"KZ", threeLetterCode:"KAZ", numericCode:398),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Jordan")},  twoLetterCode:"JO", threeLetterCode:"JOR", numericCode:400),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Kenya")},  twoLetterCode:"KE", threeLetterCode:"KEN", numericCode:404),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Korea (the Democratic People's Republic of)")},  twoLetterCode:"KP", threeLetterCode:"PRK", numericCode:408),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Korea (the Republic of)")},  twoLetterCode:"KR", threeLetterCode:"KOR", numericCode:410),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Kuwait")},  twoLetterCode:"KW", threeLetterCode:"KWT", numericCode:414),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Kyrgyzstan")},  twoLetterCode:"KG", threeLetterCode:"KGZ", numericCode:417),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Lao People's Democratic Republic (the)")},  twoLetterCode:"LA", threeLetterCode:"LAO", numericCode:418),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Lebanon")},  twoLetterCode:"LB", threeLetterCode:"LBN", numericCode:422),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Lesotho")},  twoLetterCode:"LS", threeLetterCode:"LSO", numericCode:426),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Latvia")},  twoLetterCode:"LV", threeLetterCode:"LVA", numericCode:428),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Liberia")},  twoLetterCode:"LR", threeLetterCode:"LBR", numericCode:430),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Libya")},  twoLetterCode:"LY", threeLetterCode:"LBY", numericCode:434),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Liechtenstein")},  twoLetterCode:"LI", threeLetterCode:"LIE", numericCode:438),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Lithuania")},  twoLetterCode:"LT", threeLetterCode:"LTU", numericCode:440),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Luxembourg")},  twoLetterCode:"LU", threeLetterCode:"LUX", numericCode:442),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Macao")},  twoLetterCode:"MO", threeLetterCode:"MAC", numericCode:446),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Madagascar")},  twoLetterCode:"MG", threeLetterCode:"MDG", numericCode:450),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Malawi")},  twoLetterCode:"MW", threeLetterCode:"MWI", numericCode:454),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Malaysia")},  twoLetterCode:"MY", threeLetterCode:"MYS", numericCode:458),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Maldives")},  twoLetterCode:"MV", threeLetterCode:"MDV", numericCode:462),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Mali")},  twoLetterCode:"ML", threeLetterCode:"MLI", numericCode:466),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Malta")},  twoLetterCode:"MT", threeLetterCode:"MLT", numericCode:470),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Martinique")},  twoLetterCode:"MQ", threeLetterCode:"MTQ", numericCode:474),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Mauritania")},  twoLetterCode:"MR", threeLetterCode:"MRT", numericCode:478),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Mauritius")},  twoLetterCode:"MU", threeLetterCode:"MUS", numericCode:480),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Mexico")},  twoLetterCode:"MX", threeLetterCode:"MEX", numericCode:484),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Monaco")},  twoLetterCode:"MC", threeLetterCode:"MCO", numericCode:492),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Mongolia")},  twoLetterCode:"MN", threeLetterCode:"MNG", numericCode:496),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Moldova (the Republic of)")},  twoLetterCode:"MD", threeLetterCode:"MDA", numericCode:498),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Montenegro")},  twoLetterCode:"ME", threeLetterCode:"MNE", numericCode:499),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Montserrat")},  twoLetterCode:"MS", threeLetterCode:"MSR", numericCode:500),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Morocco")},  twoLetterCode:"MA", threeLetterCode:"MAR", numericCode:504),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Mozambique")},  twoLetterCode:"MZ", threeLetterCode:"MOZ", numericCode:508),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Oman")},  twoLetterCode:"OM", threeLetterCode:"OMN", numericCode:512),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Namibia")},  twoLetterCode:"NA", threeLetterCode:"NAM", numericCode:516),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Nauru")},  twoLetterCode:"NR", threeLetterCode:"NRU", numericCode:520),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Nepal")},  twoLetterCode:"NP", threeLetterCode:"NPL", numericCode:524),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Netherlands (Kingdom of the)")},  twoLetterCode:"NL", threeLetterCode:"NLD", numericCode:528),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Curaçao")},  twoLetterCode:"CW", threeLetterCode:"CUW", numericCode:531),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Aruba")},  twoLetterCode:"AW", threeLetterCode:"ABW", numericCode:533),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Sint Maarten (Dutch part)")},  twoLetterCode:"SX", threeLetterCode:"SXM", numericCode:534),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Bonaire, Sint Eustatius and Saba")},  twoLetterCode:"BQ", threeLetterCode:"BES", numericCode:535),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "New Caledonia")},  twoLetterCode:"NC", threeLetterCode:"NCL", numericCode:540),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Vanuatu")},  twoLetterCode:"VU", threeLetterCode:"VUT", numericCode:548),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "New Zealand")},  twoLetterCode:"NZ", threeLetterCode:"NZL", numericCode:554),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Nicaragua")},  twoLetterCode:"NI", threeLetterCode:"NIC", numericCode:558),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Niger (the)")},  twoLetterCode:"NE", threeLetterCode:"NER", numericCode:562),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Nigeria")},  twoLetterCode:"NG", threeLetterCode:"NGA", numericCode:566),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Niue")},  twoLetterCode:"NU", threeLetterCode:"NIU", numericCode:570),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Norfolk Island")},  twoLetterCode:"NF", threeLetterCode:"NFK", numericCode:574),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Norway")},  twoLetterCode:"NO", threeLetterCode:"NOR", numericCode:578),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Northern Mariana Islands (the)")},  twoLetterCode:"MP", threeLetterCode:"MNP", numericCode:580),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "United States Minor Outlying Islands (the)")},  twoLetterCode:"UM", threeLetterCode:"UMI", numericCode:581),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Micronesia (Federated States of)")},  twoLetterCode:"FM", threeLetterCode:"FSM", numericCode:583),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Marshall Islands (the)")},  twoLetterCode:"MH", threeLetterCode:"MHL", numericCode:584),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Palau")},  twoLetterCode:"PW", threeLetterCode:"PLW", numericCode:585),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Pakistan")},  twoLetterCode:"PK", threeLetterCode:"PAK", numericCode:586),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Panama")},  twoLetterCode:"PA", threeLetterCode:"PAN", numericCode:591),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Papua New Guinea")},  twoLetterCode:"PG", threeLetterCode:"PNG", numericCode:598),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Paraguay")},  twoLetterCode:"PY", threeLetterCode:"PRY", numericCode:600),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Peru")},  twoLetterCode:"PE", threeLetterCode:"PER", numericCode:604),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Philippines (the)")},  twoLetterCode:"PH", threeLetterCode:"PHL", numericCode:608),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Pitcairn")},  twoLetterCode:"PN", threeLetterCode:"PCN", numericCode:612),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Poland")},  twoLetterCode:"PL", threeLetterCode:"POL", numericCode:616),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Portugal")},  twoLetterCode:"PT", threeLetterCode:"PRT", numericCode:620),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Guinea-Bissau")},  twoLetterCode:"GW", threeLetterCode:"GNB", numericCode:624),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Timor-Leste")},  twoLetterCode:"TL", threeLetterCode:"TLS", numericCode:626),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Puerto Rico")},  twoLetterCode:"PR", threeLetterCode:"PRI", numericCode:630),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Qatar")},  twoLetterCode:"QA", threeLetterCode:"QAT", numericCode:634),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Réunion")},  twoLetterCode:"RE", threeLetterCode:"REU", numericCode:638),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Romania")},  twoLetterCode:"RO", threeLetterCode:"ROU", numericCode:642),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Russian Federation (the)")},  twoLetterCode:"RU", threeLetterCode:"RUS", numericCode:643),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Rwanda")},  twoLetterCode:"RW", threeLetterCode:"RWA", numericCode:646),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Saint Barthélemy")},  twoLetterCode:"BL", threeLetterCode:"BLM", numericCode:652),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Saint Helena, Ascension and Tristan da Cunha")},  twoLetterCode:"SH", threeLetterCode:"SHN", numericCode:654),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Saint Kitts and Nevis")},  twoLetterCode:"KN", threeLetterCode:"KNA", numericCode:659),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Anguilla")},  twoLetterCode:"AI", threeLetterCode:"AIA", numericCode:660),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Saint Lucia")},  twoLetterCode:"LC", threeLetterCode:"LCA", numericCode:662),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Saint Martin (French part)")},  twoLetterCode:"MF", threeLetterCode:"MAF", numericCode:663),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Saint Pierre and Miquelon")},  twoLetterCode:"PM", threeLetterCode:"SPM", numericCode:666),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Saint Vincent and the Grenadines")},  twoLetterCode:"VC", threeLetterCode:"VCT", numericCode:670),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "San Marino")},  twoLetterCode:"SM", threeLetterCode:"SMR", numericCode:674),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Sao Tome and Principe")},  twoLetterCode:"ST", threeLetterCode:"STP", numericCode:678),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Saudi Arabia")},  twoLetterCode:"SA", threeLetterCode:"SAU", numericCode:682),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Senegal")},  twoLetterCode:"SN", threeLetterCode:"SEN", numericCode:686),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Serbia")},  twoLetterCode:"RS", threeLetterCode:"SRB", numericCode:688),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Seychelles")},  twoLetterCode:"SC", threeLetterCode:"SYC", numericCode:690),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Sierra Leone")},  twoLetterCode:"SL", threeLetterCode:"SLE", numericCode:694),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Singapore")},  twoLetterCode:"SG", threeLetterCode:"SGP", numericCode:702),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Slovakia")},  twoLetterCode:"SK", threeLetterCode:"SVK", numericCode:703),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Viet Nam")},  twoLetterCode:"VN", threeLetterCode:"VNM", numericCode:704),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Slovenia")},  twoLetterCode:"SI", threeLetterCode:"SVN", numericCode:705),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Somalia")},  twoLetterCode:"SO", threeLetterCode:"SOM", numericCode:706),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "South Africa")},  twoLetterCode:"ZA", threeLetterCode:"ZAF", numericCode:710),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Zimbabwe")},  twoLetterCode:"ZW", threeLetterCode:"ZWE", numericCode:716),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Spain")},  twoLetterCode:"ES", threeLetterCode:"ESP", numericCode:724),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "South Sudan")},  twoLetterCode:"SS", threeLetterCode:"SSD", numericCode:728),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Sudan (the)")},  twoLetterCode:"SD", threeLetterCode:"SDN", numericCode:729),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Western Sahara*")},  twoLetterCode:"EH", threeLetterCode:"ESH", numericCode:732),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Suriname")},  twoLetterCode:"SR", threeLetterCode:"SUR", numericCode:740),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Svalbard and Jan Mayen")},  twoLetterCode:"SJ", threeLetterCode:"SJM", numericCode:744),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Eswatini")},  twoLetterCode:"SZ", threeLetterCode:"SWZ", numericCode:748),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Sweden")},  twoLetterCode:"SE", threeLetterCode:"SWE", numericCode:752),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Switzerland")},  twoLetterCode:"CH", threeLetterCode:"CHE", numericCode:756),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Syrian Arab Republic (the)")},  twoLetterCode:"SY", threeLetterCode:"SYR", numericCode:760),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Tajikistan")},  twoLetterCode:"TJ", threeLetterCode:"TJK", numericCode:762),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Thailand")},  twoLetterCode:"TH", threeLetterCode:"THA", numericCode:764),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Togo")},  twoLetterCode:"TG", threeLetterCode:"TGO", numericCode:768),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Tokelau")},  twoLetterCode:"TK", threeLetterCode:"TKL", numericCode:772),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Tonga")},  twoLetterCode:"TO", threeLetterCode:"TON", numericCode:776),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Trinidad and Tobago")},  twoLetterCode:"TT", threeLetterCode:"TTO", numericCode:780),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "United Arab Emirates (the)")},  twoLetterCode:"AE", threeLetterCode:"ARE", numericCode:784),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Tunisia")},  twoLetterCode:"TN", threeLetterCode:"TUN", numericCode:788),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Türkiye")},  twoLetterCode:"TR", threeLetterCode:"TUR", numericCode:792),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Turkmenistan")},  twoLetterCode:"TM", threeLetterCode:"TKM", numericCode:795),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Turks and Caicos Islands (the)")},  twoLetterCode:"TC", threeLetterCode:"TCA", numericCode:796),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Tuvalu")},  twoLetterCode:"TV", threeLetterCode:"TUV", numericCode:798),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Uganda")},  twoLetterCode:"UG", threeLetterCode:"UGA", numericCode:800),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Ukraine")},  twoLetterCode:"UA", threeLetterCode:"UKR", numericCode:804),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "North Macedonia")},  twoLetterCode:"MK", threeLetterCode:"MKD", numericCode:807),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Egypt")},  twoLetterCode:"EG", threeLetterCode:"EGY", numericCode:818),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "United Kingdom of Great Britain and Northern Ireland (the)")},  twoLetterCode:"GB", threeLetterCode:"GBR", numericCode:826),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Guernsey")},  twoLetterCode:"GG", threeLetterCode:"GGY", numericCode:831),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Jersey")},  twoLetterCode:"JE", threeLetterCode:"JEY", numericCode:832),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Isle of Man")},  twoLetterCode:"IM", threeLetterCode:"IMN", numericCode:833),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Tanzania, the United Republic of")},  twoLetterCode:"TZ", threeLetterCode:"TZA", numericCode:834),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "United States of America (the)")},  twoLetterCode:"US", threeLetterCode:"USA", numericCode:840),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Virgin Islands (U.S.)")},  twoLetterCode:"VI", threeLetterCode:"VIR", numericCode:850),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Burkina Faso")},  twoLetterCode:"BF", threeLetterCode:"BFA", numericCode:854),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Uruguay")},  twoLetterCode:"UY", threeLetterCode:"URY", numericCode:858),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Uzbekistan")},  twoLetterCode:"UZ", threeLetterCode:"UZB", numericCode:860),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Venezuela (Bolivarian Republic of)")},  twoLetterCode:"VE", threeLetterCode:"VEN", numericCode:862),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Wallis and Futuna")},  twoLetterCode:"WF", threeLetterCode:"WLF", numericCode:876),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Samoa")},  twoLetterCode:"WS", threeLetterCode:"WSM", numericCode:882),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Yemen")},  twoLetterCode:"YE", threeLetterCode:"YEM", numericCode:887),
                new Country(new List<DisplayInfo>(){new DisplayInfo("eng", "Zambia")},  twoLetterCode:"ZM", threeLetterCode:"ZMB", numericCode:894)
            };

#if NET8_0_OR_GREATER
            AllCountries = countries.ToFrozenSet();
#else
            AllCountries = countries.AsReadOnly();
#endif

        }

    }
}
